-- ChainLoom Semantic View v2.1
-- Conservative foundation build.
-- RAW sources are explicitly qualified.
-- Metrics are same-logical-table aggregations only.
-- NON ADDITIVE BY is intentionally deferred until this foundation validates.

USE DATABASE CHAINLOOM;
USE SCHEMA SEMANTIC;

CREATE OR REPLACE SEMANTIC VIEW CHAINLOOM_ANALYTICS
TABLES (
  supplier AS CHAINLOOM.RAW.SUPPLIER PRIMARY KEY (SUPPLIER_ID),
  part AS CHAINLOOM.RAW.PART PRIMARY KEY (PART_ID),
  product AS CHAINLOOM.RAW.PRODUCT PRIMARY KEY (PRODUCT_ID),
  plant AS CHAINLOOM.RAW.PLANT PRIMARY KEY (PLANT_ID),
  customer AS CHAINLOOM.RAW.CUSTOMER PRIMARY KEY (CUSTOMER_ID),
  carrier AS CHAINLOOM.RAW.CARRIER PRIMARY KEY (CARRIER_ID),
  supplier_part AS CHAINLOOM.RAW.SUPPLIER_PART PRIMARY KEY (SUPPLIER_PART_ID),
  product_part AS CHAINLOOM.RAW.PRODUCT_PART PRIMARY KEY (PRODUCT_PART_ID),
  purchase_order_line AS CHAINLOOM.RAW.PURCHASE_ORDER_LINE PRIMARY KEY (PO_LINE_ID),
  supply_receipt AS CHAINLOOM.RAW.SUPPLY_RECEIPT PRIMARY KEY (RECEIPT_ID),
  inventory AS CHAINLOOM.RAW.INVENTORY PRIMARY KEY (INVENTORY_SNAPSHOT_ID),
  production AS CHAINLOOM.RAW.PRODUCTION PRIMARY KEY (PRODUCTION_ID),
  quality AS CHAINLOOM.RAW.QUALITY PRIMARY KEY (INSPECTION_ID),
  order_line AS CHAINLOOM.RAW.ORDER_LINE PRIMARY KEY (ORDER_LINE_ID),
  shipment AS CHAINLOOM.RAW.SHIPMENT PRIMARY KEY (SHIPMENT_ID)
)
RELATIONSHIPS (
  supplier_part_supplier AS supplier_part (SUPPLIER_ID) REFERENCES supplier (SUPPLIER_ID),
  supplier_part_part AS supplier_part (PART_ID) REFERENCES part (PART_ID),
  product_part_product AS product_part (PRODUCT_ID) REFERENCES product (PRODUCT_ID),
  product_part_part AS product_part (PART_ID) REFERENCES part (PART_ID),
  po_supplier AS purchase_order_line (SUPPLIER_ID) REFERENCES supplier (SUPPLIER_ID),
  po_part AS purchase_order_line (PART_ID) REFERENCES part (PART_ID),
  po_plant AS purchase_order_line (PLANT_ID) REFERENCES plant (PLANT_ID),
  receipt_po AS supply_receipt (PO_LINE_ID) REFERENCES purchase_order_line (PO_LINE_ID),
  receipt_supplier AS supply_receipt (SUPPLIER_ID) REFERENCES supplier (SUPPLIER_ID),
  receipt_part AS supply_receipt (PART_ID) REFERENCES part (PART_ID),
  receipt_plant AS supply_receipt (PLANT_ID) REFERENCES plant (PLANT_ID),
  inventory_part AS inventory (PART_ID) REFERENCES part (PART_ID),
  inventory_plant AS inventory (PLANT_ID) REFERENCES plant (PLANT_ID),
  production_product AS production (PRODUCT_ID) REFERENCES product (PRODUCT_ID),
  production_plant AS production (PLANT_ID) REFERENCES plant (PLANT_ID),
  quality_supplier AS quality (SUPPLIER_ID) REFERENCES supplier (SUPPLIER_ID),
  quality_part AS quality (PART_ID) REFERENCES part (PART_ID),
  quality_plant AS quality (PLANT_ID) REFERENCES plant (PLANT_ID),
  order_customer AS order_line (CUSTOMER_ID) REFERENCES customer (CUSTOMER_ID),
  order_product AS order_line (PRODUCT_ID) REFERENCES product (PRODUCT_ID),
  order_plant AS order_line (PLANT_ID) REFERENCES plant (PLANT_ID),
  shipment_order AS shipment (ORDER_LINE_ID) REFERENCES order_line (ORDER_LINE_ID),
  shipment_customer AS shipment (CUSTOMER_ID) REFERENCES customer (CUSTOMER_ID),
  shipment_product AS shipment (PRODUCT_ID) REFERENCES product (PRODUCT_ID),
  shipment_plant AS shipment (PLANT_ID) REFERENCES plant (PLANT_ID),
  shipment_carrier AS shipment (CARRIER_ID) REFERENCES carrier (CARRIER_ID)
)
FACTS (
  purchase_order_line.ordered_quantity_fact AS purchase_order_line.ORDERED_QUANTITY,
  purchase_order_line.unit_cost_fact AS purchase_order_line.UNIT_COST,
  supply_receipt.received_quantity_fact AS supply_receipt.RECEIVED_QUANTITY,
  supply_receipt.accepted_quantity_fact AS supply_receipt.ACCEPTED_QUANTITY,
  supply_receipt.rejected_quantity_fact AS supply_receipt.REJECTED_QUANTITY,
  inventory.on_hand_quantity_fact AS inventory.ON_HAND_QUANTITY,
  inventory.reserved_quantity_fact AS inventory.RESERVED_QUANTITY,
  inventory.available_quantity_fact AS inventory.AVAILABLE_QUANTITY,
  inventory.safety_stock_quantity_fact AS inventory.SAFETY_STOCK_QUANTITY,
  production.planned_quantity_fact AS production.PLANNED_QUANTITY,
  production.produced_quantity_fact AS production.PRODUCED_QUANTITY,
  production.downtime_hours_fact AS production.DOWNTIME_HOURS,
  quality.inspected_quantity_fact AS quality.INSPECTED_QUANTITY,
  quality.defective_quantity_fact AS quality.DEFECTIVE_QUANTITY,
  order_line.ordered_quantity_fact AS order_line.ORDERED_QUANTITY,
  order_line.fulfilled_quantity_fact AS order_line.FULFILLED_QUANTITY,
  shipment.shipped_quantity_fact AS shipment.SHIPPED_QUANTITY
)
DIMENSIONS (
  supplier.supplier_id AS supplier.SUPPLIER_ID,
  supplier.supplier_name AS supplier.SUPPLIER_NAME,
  supplier.supplier_region AS supplier.SUPPLIER_REGION,
  supplier.supplier_tier AS supplier.SUPPLIER_TIER,
  supplier.supplier_status AS supplier.SUPPLIER_STATUS,
  part.part_id AS part.PART_ID,
  part.part_name AS part.PART_NAME,
  part.part_category AS part.PART_CATEGORY,
  part.criticality AS part.CRITICALITY,
  product.product_id AS product.PRODUCT_ID,
  product.product_name AS product.PRODUCT_NAME,
  product.product_family AS product.PRODUCT_FAMILY,
  product.product_category AS product.PRODUCT_CATEGORY,
  plant.plant_id AS plant.PLANT_ID,
  plant.plant_name AS plant.PLANT_NAME,
  plant.region AS plant.REGION,
  plant.plant_type AS plant.PLANT_TYPE,
  customer.customer_id AS customer.CUSTOMER_ID,
  customer.customer_name AS customer.CUSTOMER_NAME,
  customer.customer_segment AS customer.CUSTOMER_SEGMENT,
  customer.customer_region AS customer.CUSTOMER_REGION,
  customer.customer_priority AS customer.CUSTOMER_PRIORITY,
  carrier.carrier_id AS carrier.CARRIER_ID,
  carrier.carrier_name AS carrier.CARRIER_NAME,
  carrier.service_level AS carrier.SERVICE_LEVEL,
  carrier.carrier_region AS carrier.CARRIER_REGION,
  supplier_part.supplier_part_id AS supplier_part.SUPPLIER_PART_ID,
  supplier_part.preferred_supplier_flag AS supplier_part.PREFERRED_SUPPLIER_FLAG,
  product_part.product_part_id AS product_part.PRODUCT_PART_ID,
  product_part.quantity_per_product AS product_part.QUANTITY_PER_PRODUCT,
  product_part.critical_part_flag AS product_part.CRITICAL_PART_FLAG,
  purchase_order_line.po_line_id AS purchase_order_line.PO_LINE_ID,
  purchase_order_line.po_id AS purchase_order_line.PO_ID,
  purchase_order_line.order_date AS purchase_order_line.ORDER_DATE,
  purchase_order_line.promised_receipt_date AS purchase_order_line.PROMISED_RECEIPT_DATE,
  purchase_order_line.po_line_status AS purchase_order_line.PO_LINE_STATUS,
  supply_receipt.receipt_id AS supply_receipt.RECEIPT_ID,
  supply_receipt.receipt_date AS supply_receipt.RECEIPT_DATE,
  supply_receipt.receipt_status AS supply_receipt.RECEIPT_STATUS,
  inventory.inventory_snapshot_id AS inventory.INVENTORY_SNAPSHOT_ID,
  inventory.snapshot_date AS inventory.SNAPSHOT_DATE,
  production.production_id AS production.PRODUCTION_ID,
  production.production_date AS production.PRODUCTION_DATE,
  production.production_status AS production.PRODUCTION_STATUS,
  quality.inspection_id AS quality.INSPECTION_ID,
  quality.inspection_date AS quality.INSPECTION_DATE,
  quality.defect_type AS quality.DEFECT_TYPE,
  quality.inspection_status AS quality.INSPECTION_STATUS,
  order_line.order_line_id AS order_line.ORDER_LINE_ID,
  order_line.order_id AS order_line.ORDER_ID,
  order_line.order_date AS order_line.ORDER_DATE,
  order_line.promised_date AS order_line.PROMISED_DATE,
  order_line.order_status AS order_line.ORDER_STATUS,
  shipment.shipment_id AS shipment.SHIPMENT_ID,
  shipment.ship_date AS shipment.SHIP_DATE,
  shipment.promised_date AS shipment.PROMISED_DATE,
  shipment.actual_delivery_date AS shipment.ACTUAL_DELIVERY_DATE,
  shipment.shipment_status AS shipment.SHIPMENT_STATUS,
  shipment.delay_reason AS shipment.DELAY_REASON
)
METRICS (
  purchase_order_line.po_line_count AS COUNT(purchase_order_line.PO_LINE_ID),
  purchase_order_line.ordered_quantity AS SUM(purchase_order_line.ORDERED_QUANTITY),
  supply_receipt.receipt_count AS COUNT(supply_receipt.RECEIPT_ID),
  supply_receipt.received_quantity AS SUM(supply_receipt.RECEIVED_QUANTITY),
  supply_receipt.accepted_quantity AS SUM(supply_receipt.ACCEPTED_QUANTITY),
  supply_receipt.rejected_quantity AS SUM(supply_receipt.REJECTED_QUANTITY),
  inventory.snapshot_count AS COUNT(inventory.INVENTORY_SNAPSHOT_ID),
  inventory.available_quantity AS SUM(inventory.AVAILABLE_QUANTITY),
  inventory.safety_stock_quantity AS SUM(inventory.SAFETY_STOCK_QUANTITY),
  production.production_record_count AS COUNT(production.PRODUCTION_ID),
  production.production_day_count AS COUNT(DISTINCT production.PRODUCTION_DATE),
  production.planned_quantity AS SUM(production.PLANNED_QUANTITY),
  production.produced_quantity AS SUM(production.PRODUCED_QUANTITY),
  production.downtime_hours AS SUM(production.DOWNTIME_HOURS),
  quality.inspected_quantity AS SUM(quality.INSPECTED_QUANTITY),
  quality.defective_quantity AS SUM(quality.DEFECTIVE_QUANTITY),
  order_line.order_line_count AS COUNT(order_line.ORDER_LINE_ID),
  order_line.ordered_quantity AS SUM(order_line.ORDERED_QUANTITY),
  order_line.fulfilled_quantity AS SUM(order_line.FULFILLED_QUANTITY),
  shipment.shipment_count AS COUNT(shipment.SHIPMENT_ID),
  shipment.shipped_quantity AS SUM(shipment.SHIPPED_QUANTITY)
)
COMMENT = 'ChainLoom semantic foundation: row-level RAW logical tables, conformed dimensions, explicit relationships, and same-table governed metrics. Cross-fact derived metrics are intentionally deferred.'
;
