-- ChainLoom
-- RAW validation
-- Version: 1.1
-- Purpose: Validate referential integrity, grain assumptions, and scenario ground truth.

USE DATABASE CHAINLOOM;
USE SCHEMA RAW;

-- ============================================================
-- 1. Expected master-data counts
-- ============================================================
SELECT
    'SUPPLIER' AS CHECK_NAME,
    IFF(COUNT(*) = 8, 'PASS', 'FAIL') AS STATUS,
    COUNT(*) AS ACTUAL_COUNT,
    8 AS EXPECTED_COUNT
FROM SUPPLIER
UNION ALL
SELECT 'PART', IFF(COUNT(*) = 10, 'PASS', 'FAIL'), COUNT(*), 10 FROM PART
UNION ALL
SELECT 'PRODUCT', IFF(COUNT(*) = 6, 'PASS', 'FAIL'), COUNT(*), 6 FROM PRODUCT
UNION ALL
SELECT 'PLANT', IFF(COUNT(*) = 3, 'PASS', 'FAIL'), COUNT(*), 3 FROM PLANT
UNION ALL
SELECT 'CUSTOMER', IFF(COUNT(*) = 30, 'PASS', 'FAIL'), COUNT(*), 30 FROM CUSTOMER
UNION ALL
SELECT 'CARRIER', IFF(COUNT(*) = 4, 'PASS', 'FAIL'), COUNT(*), 4 FROM CARRIER
UNION ALL
SELECT 'DATE_DIM', IFF(COUNT(*) = 92, 'PASS', 'FAIL'), COUNT(*), 92 FROM DATE_DIM
ORDER BY CHECK_NAME;

-- ============================================================
-- 2. Orphan checks
-- ============================================================
SELECT 'PO -> SUPPLIER' AS CHECK_NAME, COUNT(*) AS ORPHAN_COUNT
FROM PURCHASE_ORDER_LINE PO
LEFT JOIN SUPPLIER S ON S.SUPPLIER_ID = PO.SUPPLIER_ID
WHERE S.SUPPLIER_ID IS NULL
UNION ALL
SELECT 'PO -> PART', COUNT(*)
FROM PURCHASE_ORDER_LINE PO
LEFT JOIN PART P ON P.PART_ID = PO.PART_ID
WHERE P.PART_ID IS NULL
UNION ALL
SELECT 'PO -> PLANT', COUNT(*)
FROM PURCHASE_ORDER_LINE PO
LEFT JOIN PLANT PL ON PL.PLANT_ID = PO.PLANT_ID
WHERE PL.PLANT_ID IS NULL
UNION ALL
SELECT 'RECEIPT -> PO', COUNT(*)
FROM SUPPLY_RECEIPT R
LEFT JOIN PURCHASE_ORDER_LINE PO ON PO.PO_LINE_ID = R.PO_LINE_ID
WHERE PO.PO_LINE_ID IS NULL
UNION ALL
SELECT 'ORDER -> CUSTOMER', COUNT(*)
FROM ORDER_LINE O
LEFT JOIN CUSTOMER C ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL
UNION ALL
SELECT 'ORDER -> PRODUCT', COUNT(*)
FROM ORDER_LINE O
LEFT JOIN PRODUCT P ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL
UNION ALL
SELECT 'SHIPMENT -> ORDER', COUNT(*)
FROM SHIPMENT SH
LEFT JOIN ORDER_LINE O ON O.ORDER_LINE_ID = SH.ORDER_LINE_ID
WHERE O.ORDER_LINE_ID IS NULL
UNION ALL
SELECT 'SHIPMENT -> CARRIER', COUNT(*)
FROM SHIPMENT SH
LEFT JOIN CARRIER C ON C.CARRIER_ID = SH.CARRIER_ID
WHERE C.CARRIER_ID IS NULL
ORDER BY CHECK_NAME;

-- ============================================================
-- 3. Grain checks
-- ============================================================
SELECT
    'INVENTORY_DUPLICATE_PART_PLANT_DATE' AS CHECK_NAME,
    COUNT(*) AS DUPLICATE_GROUPS
FROM (
    SELECT PART_ID, PLANT_ID, SNAPSHOT_DATE
    FROM INVENTORY
    GROUP BY PART_ID, PLANT_ID, SNAPSHOT_DATE
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT
    'PO_LINE_DUPLICATE_ID',
    COUNT(*)
FROM (
    SELECT PO_LINE_ID FROM PURCHASE_ORDER_LINE
    GROUP BY PO_LINE_ID HAVING COUNT(*) > 1
)
UNION ALL
SELECT
    'ORDER_LINE_DUPLICATE_ID',
    COUNT(*)
FROM (
    SELECT ORDER_LINE_ID FROM ORDER_LINE
    GROUP BY ORDER_LINE_ID HAVING COUNT(*) > 1
)
UNION ALL
SELECT
    'SHIPMENT_DUPLICATE_ID',
    COUNT(*)
FROM (
    SELECT SHIPMENT_ID FROM SHIPMENT
    GROUP BY SHIPMENT_ID HAVING COUNT(*) > 1
);

-- ============================================================
-- 4. Data-quality checks
-- ============================================================
SELECT 'RECEIPT_QUANTITY_BALANCE' AS CHECK_NAME, COUNT(*) AS FAILURE_COUNT
FROM SUPPLY_RECEIPT
WHERE RECEIVED_QUANTITY <> ACCEPTED_QUANTITY + REJECTED_QUANTITY
UNION ALL
SELECT 'NEGATIVE_INVENTORY_AVAILABLE', COUNT(*)
FROM INVENTORY
WHERE AVAILABLE_QUANTITY < 0
UNION ALL
SELECT 'ORDER_FULFILLED_GT_ORDERED', COUNT(*)
FROM ORDER_LINE
WHERE FULFILLED_QUANTITY > ORDERED_QUANTITY
UNION ALL
SELECT 'SHIPMENT_QTY_GT_ORDER_LINE_FULFILLED', COUNT(*)
FROM SHIPMENT SH
JOIN ORDER_LINE O ON O.ORDER_LINE_ID = SH.ORDER_LINE_ID
WHERE SH.SHIPPED_QUANTITY > O.FULFILLED_QUANTITY
UNION ALL
SELECT 'QUALITY_DEFECT_GT_INSPECTED', COUNT(*)
FROM QUALITY
WHERE DEFECTIVE_QUANTITY > INSPECTED_QUANTITY
ORDER BY CHECK_NAME;

-- ============================================================
-- 5. Ground-truth disruption checks
-- ============================================================
SELECT
    'DISRUPTION_PO_LINES' AS CHECK_NAME,
    COUNT(*) AS ROW_COUNT
FROM PURCHASE_ORDER_LINE
WHERE SUPPLIER_ID = 'S017'
  AND PART_ID = 'P104'
  AND PLANT_ID = 'PL03'
  AND ORDER_DATE >= '2026-07-24'::DATE

UNION ALL

SELECT
    'DISRUPTION_LATE_RECEIPTS',
    COUNT(*)
FROM SUPPLY_RECEIPT
WHERE SUPPLIER_ID = 'S017'
  AND PART_ID = 'P104'
  AND RECEIPT_DATE > '2026-08-01'::DATE

UNION ALL

SELECT
    'DISRUPTION_INVENTORY_SNAPSHOTS',
    COUNT(*)
FROM INVENTORY
WHERE PART_ID = 'P104'
  AND PLANT_ID = 'PL03'
  AND SNAPSHOT_DATE >= '2026-08-01'::DATE

UNION ALL

SELECT
    'DISRUPTION_CONSTRAINED_PRODUCTION',
    COUNT(*)
FROM PRODUCTION
WHERE PLANT_ID = 'PL03'
  AND PRODUCT_ID IN ('PR202','PR203','PR204','PR206')
  AND PRODUCTION_STATUS = 'Constrained'

UNION ALL

SELECT
    'DISRUPTION_IMPACTED_ORDERS',
    COUNT(*)
FROM ORDER_LINE
WHERE ORDER_LINE_ID IN ('OL-900001','OL-900002','OL-900003','OL-900004','OL-900005');

-- ============================================================
-- 6. Critical scenario evidence preview
-- ============================================================
SELECT
    PO.PO_LINE_ID,
    PO.SUPPLIER_ID,
    PO.PART_ID,
    PO.PLANT_ID,
    PO.PROMISED_RECEIPT_DATE,
    R.RECEIPT_DATE,
    DATEDIFF(day, PO.PROMISED_RECEIPT_DATE, R.RECEIPT_DATE) AS RECEIPT_DELAY_DAYS
FROM PURCHASE_ORDER_LINE PO
LEFT JOIN SUPPLY_RECEIPT R
  ON R.PO_LINE_ID = PO.PO_LINE_ID
WHERE PO.SUPPLIER_ID = 'S017'
  AND PO.PART_ID = 'P104'
  AND PO.PLANT_ID = 'PL03'
ORDER BY PO.ORDER_DATE;

SELECT
    SNAPSHOT_DATE,
    AVAILABLE_QUANTITY,
    SAFETY_STOCK_QUANTITY
FROM INVENTORY
WHERE PART_ID = 'P104'
  AND PLANT_ID = 'PL03'
ORDER BY SNAPSHOT_DATE;

SELECT
    ORDER_LINE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    PLANT_ID,
    PROMISED_DATE,
    ORDERED_QUANTITY,
    FULFILLED_QUANTITY,
    ORDER_STATUS
FROM ORDER_LINE
WHERE ORDER_LINE_ID LIKE 'OL-90000%'
ORDER BY ORDER_LINE_ID;
