-- ChainLoom
-- CURATED layer
-- 01_supplier_performance.sql
-- Grain: one row per supplier-part sourcing relationship.

USE DATABASE CHAINLOOM;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW V_SUPPLIER_PERFORMANCE
COMMENT = 'Curated supplier-part performance surface; grain: one row per supplier-part relationship'
AS
WITH PO AS (
    SELECT
        POL.SUPPLIER_ID,
        POL.PART_ID,
        COUNT(*) AS PO_LINE_COUNT,
        SUM(POL.ORDERED_QUANTITY) AS ORDERED_QUANTITY,
        AVG(DATEDIFF('day', POL.ORDER_DATE, POL.PROMISED_RECEIPT_DATE)) AS PROMISED_LEAD_TIME_DAYS
    FROM CHAINLOOM.RAW.PURCHASE_ORDER_LINE POL
    GROUP BY POL.SUPPLIER_ID, POL.PART_ID
),
RECEIPT AS (
    SELECT
        R.PO_LINE_ID,
        R.SUPPLIER_ID,
        R.PART_ID,
        COUNT(*) AS RECEIPT_COUNT,
        SUM(R.RECEIVED_QUANTITY) AS RECEIVED_QUANTITY,
        SUM(R.ACCEPTED_QUANTITY) AS ACCEPTED_QUANTITY,
        SUM(R.REJECTED_QUANTITY) AS REJECTED_QUANTITY,
        AVG(
            DATEDIFF(
                'day',
                POL.PROMISED_RECEIPT_DATE,
                R.RECEIPT_DATE
            )
        ) AS AVG_RECEIPT_DELAY_DAYS,
        SUM(
            IFF(R.RECEIPT_DATE <= POL.PROMISED_RECEIPT_DATE, 1, 0)
        ) AS ON_TIME_RECEIPTS
    FROM CHAINLOOM.RAW.SUPPLY_RECEIPT R
    JOIN CHAINLOOM.RAW.PURCHASE_ORDER_LINE POL
      ON R.PO_LINE_ID = POL.PO_LINE_ID
    GROUP BY
        R.PO_LINE_ID,
        R.SUPPLIER_ID,
        R.PART_ID
),
RECEIPT_AGG AS (
    SELECT
        SUPPLIER_ID,
        PART_ID,
        SUM(RECEIPT_COUNT) AS RECEIPT_COUNT,
        SUM(RECEIVED_QUANTITY) AS RECEIVED_QUANTITY,
        SUM(ACCEPTED_QUANTITY) AS ACCEPTED_QUANTITY,
        SUM(REJECTED_QUANTITY) AS REJECTED_QUANTITY,
        ROUND(AVG(AVG_RECEIPT_DELAY_DAYS), 2) AS AVG_RECEIPT_DELAY_DAYS,
        SUM(ON_TIME_RECEIPTS) AS ON_TIME_RECEIPTS
    FROM RECEIPT
    GROUP BY SUPPLIER_ID, PART_ID
),
QUALITY AS (
    SELECT
        Q.SUPPLIER_ID,
        Q.PART_ID,
        SUM(Q.INSPECTED_QUANTITY) AS INSPECTED_QUANTITY,
        SUM(Q.DEFECTIVE_QUANTITY) AS DEFECTIVE_QUANTITY
    FROM CHAINLOOM.RAW.QUALITY Q
    GROUP BY Q.SUPPLIER_ID, Q.PART_ID
)
SELECT
    SP.SUPPLIER_ID,
    S.SUPPLIER_NAME,
    S.SUPPLIER_REGION,
    S.SUPPLIER_TIER,
    S.SUPPLIER_STATUS,
    SP.PART_ID,
    P.PART_NAME,
    P.PART_CATEGORY,
    P.CRITICALITY,
    SP.PREFERRED_SUPPLIER_FLAG,
    SP.ALLOCATION_PERCENT,
    COALESCE(PO.PO_LINE_COUNT, 0) AS PO_LINE_COUNT,
    COALESCE(PO.ORDERED_QUANTITY, 0) AS ORDERED_QUANTITY,
    COALESCE(RA.RECEIPT_COUNT, 0) AS RECEIPT_COUNT,
    COALESCE(RA.RECEIVED_QUANTITY, 0) AS RECEIVED_QUANTITY,
    COALESCE(RA.ACCEPTED_QUANTITY, 0) AS ACCEPTED_QUANTITY,
    COALESCE(RA.REJECTED_QUANTITY, 0) AS REJECTED_QUANTITY,
    RA.AVG_RECEIPT_DELAY_DAYS,
    ROUND(
        100.0 * RA.ON_TIME_RECEIPTS / NULLIF(RA.RECEIPT_COUNT, 0),
        2
    ) AS ON_TIME_RECEIPT_PCT,
    COALESCE(Q.INSPECTED_QUANTITY, 0) AS INSPECTED_QUANTITY,
    COALESCE(Q.DEFECTIVE_QUANTITY, 0) AS DEFECTIVE_QUANTITY,
    ROUND(
        100.0 * Q.DEFECTIVE_QUANTITY / NULLIF(Q.INSPECTED_QUANTITY, 0),
        2
    ) AS DEFECT_RATE_PCT,
    CASE
        WHEN COALESCE(RA.AVG_RECEIPT_DELAY_DAYS, 0) >= 3
          OR COALESCE(
                100.0 * Q.DEFECTIVE_QUANTITY
                / NULLIF(Q.INSPECTED_QUANTITY, 0),
                0
             ) >= 3
        THEN 'HIGH'
        WHEN COALESCE(RA.AVG_RECEIPT_DELAY_DAYS, 0) >= 1
          OR COALESCE(
                100.0 * Q.DEFECTIVE_QUANTITY
                / NULLIF(Q.INSPECTED_QUANTITY, 0),
                0
             ) >= 1
        THEN 'MEDIUM'
        ELSE 'LOW'
    END AS SUPPLY_RISK_BAND
FROM CHAINLOOM.RAW.SUPPLIER_PART SP
JOIN CHAINLOOM.RAW.SUPPLIER S
  ON SP.SUPPLIER_ID = S.SUPPLIER_ID
JOIN CHAINLOOM.RAW.PART P
  ON SP.PART_ID = P.PART_ID
LEFT JOIN PO
  ON SP.SUPPLIER_ID = PO.SUPPLIER_ID
 AND SP.PART_ID = PO.PART_ID
LEFT JOIN RECEIPT_AGG RA
  ON SP.SUPPLIER_ID = RA.SUPPLIER_ID
 AND SP.PART_ID = RA.PART_ID
LEFT JOIN QUALITY Q
  ON SP.SUPPLIER_ID = Q.SUPPLIER_ID
 AND SP.PART_ID = Q.PART_ID;
