-- ChainLoom
-- CURATED layer
-- 02_inventory_position.sql
-- Grain: one row per part-plant-snapshot date.
-- Inventory is semi-additive across time.

USE DATABASE CHAINLOOM;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW V_INVENTORY_POSITION
COMMENT = 'Curated inventory snapshot surface; grain: one row per part-plant-date; inventory quantities are semi-additive across date'
AS
SELECT
    I.INVENTORY_SNAPSHOT_ID,
    I.SNAPSHOT_DATE,
    I.PART_ID,
    P.PART_NAME,
    P.PART_CATEGORY,
    P.CRITICALITY,
    I.PLANT_ID,
    PL.PLANT_NAME,
    PL.REGION AS PLANT_REGION,
    I.ON_HAND_QUANTITY,
    I.RESERVED_QUANTITY,
    I.AVAILABLE_QUANTITY,
    I.SAFETY_STOCK_QUANTITY,
    I.AVAILABLE_QUANTITY - I.SAFETY_STOCK_QUANTITY AS SAFETY_STOCK_GAP,
    ROUND(
        100.0 * I.AVAILABLE_QUANTITY / NULLIF(I.SAFETY_STOCK_QUANTITY, 0),
        2
    ) AS AVAILABLE_TO_SAFETY_STOCK_PCT,
    IFF(
        I.AVAILABLE_QUANTITY < I.SAFETY_STOCK_QUANTITY,
        TRUE,
        FALSE
    ) AS BELOW_SAFETY_STOCK_FLAG,
    CASE
        WHEN I.AVAILABLE_QUANTITY <= 0 THEN 'STOCKOUT'
        WHEN I.AVAILABLE_QUANTITY < I.SAFETY_STOCK_QUANTITY THEN 'BELOW_SAFETY_STOCK'
        WHEN I.AVAILABLE_QUANTITY < I.SAFETY_STOCK_QUANTITY * 1.25 THEN 'NEAR_SAFETY_STOCK'
        ELSE 'HEALTHY'
    END AS INVENTORY_RISK_BAND
FROM CHAINLOOM.RAW.INVENTORY I
JOIN CHAINLOOM.RAW.PART P
  ON I.PART_ID = P.PART_ID
JOIN CHAINLOOM.RAW.PLANT PL
  ON I.PLANT_ID = PL.PLANT_ID;
