-- ChainLoom
-- CURATED layer
-- 03_production_performance.sql
-- Grain: exactly one row per plant-product-production date.
--
-- Important grain control:
-- PRODUCT_PART is many-to-many. It is therefore pre-aggregated to one row
-- per PRODUCT_ID before being joined to PRODUCTION. This prevents BOM
-- fan-out and preserves production fact grain.

USE DATABASE CHAINLOOM;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW V_PRODUCTION_PERFORMANCE
COMMENT = 'Curated production performance surface; grain: one row per plant-product-date; BOM attributes are pre-aggregated'
AS
WITH CRITICAL_BOM AS (
    SELECT
        PP.PRODUCT_ID,
        COUNT(*) AS CRITICAL_PART_COUNT,
        LISTAGG(
            PP.PART_ID || ' (' || PP.QUANTITY_PER_PRODUCT || ')',
            ', '
        ) WITHIN GROUP (ORDER BY PP.PART_ID) AS CRITICAL_PARTS,
        MAX(IFF(PP.PART_ID = 'P104', TRUE, FALSE)) AS P104_EXPOSURE_FLAG,
        MAX(IFF(PP.PART_ID = 'P104', PP.QUANTITY_PER_PRODUCT, NULL))
            AS P104_QTY_PER_PRODUCT
    FROM CHAINLOOM.RAW.PRODUCT_PART PP
    WHERE PP.CRITICAL_PART_FLAG = TRUE
    GROUP BY PP.PRODUCT_ID
)
SELECT
    PR.PRODUCTION_ID,
    PR.PRODUCTION_DATE,
    PR.PLANT_ID,
    PL.PLANT_NAME,
    PL.REGION AS PLANT_REGION,
    PR.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_FAMILY,
    P.PRODUCT_CATEGORY,
    PR.PLANNED_QUANTITY,
    PR.PRODUCED_QUANTITY,
    PR.PLANNED_QUANTITY - PR.PRODUCED_QUANTITY AS PRODUCTION_GAP_QUANTITY,
    ROUND(
        100.0 * PR.PRODUCED_QUANTITY / NULLIF(PR.PLANNED_QUANTITY, 0),
        2
    ) AS PRODUCTION_ATTAINMENT_PCT,
    PR.DOWNTIME_HOURS,
    PR.PRODUCTION_STATUS,
    IFF(PR.PRODUCTION_STATUS = 'Constrained', TRUE, FALSE)
        AS CONSTRAINT_FLAG,
    COALESCE(B.CRITICAL_PART_COUNT, 0) AS CRITICAL_PART_COUNT,
    B.CRITICAL_PARTS,
    COALESCE(B.P104_EXPOSURE_FLAG, FALSE) AS P104_EXPOSURE_FLAG,
    B.P104_QTY_PER_PRODUCT
FROM CHAINLOOM.RAW.PRODUCTION PR
JOIN CHAINLOOM.RAW.PLANT PL
  ON PR.PLANT_ID = PL.PLANT_ID
JOIN CHAINLOOM.RAW.PRODUCT P
  ON PR.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN CRITICAL_BOM B
  ON PR.PRODUCT_ID = B.PRODUCT_ID;
