-- ChainLoom
-- CURATED layer
-- 04_customer_and_shipment_performance.sql
-- Order-line and shipment surfaces remain separate to prevent fan-out.

USE DATABASE CHAINLOOM;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW V_CUSTOMER_FULFILLMENT
COMMENT = 'Curated customer fulfillment surface; grain: one row per customer order line'
AS
SELECT
    O.ORDER_LINE_ID,
    O.ORDER_ID,
    O.ORDER_DATE,
    O.PROMISED_DATE,
    O.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_SEGMENT,
    C.CUSTOMER_REGION,
    C.CUSTOMER_PRIORITY,
    O.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_FAMILY,
    P.PRODUCT_CATEGORY,
    O.PLANT_ID,
    PL.PLANT_NAME,
    PL.REGION AS PLANT_REGION,
    O.ORDERED_QUANTITY,
    O.FULFILLED_QUANTITY,
    O.ORDERED_QUANTITY - O.FULFILLED_QUANTITY AS UNFULFILLED_QUANTITY,
    ROUND(
        100.0 * O.FULFILLED_QUANTITY / NULLIF(O.ORDERED_QUANTITY, 0),
        2
    ) AS FULFILLMENT_PCT,
    O.ORDER_STATUS,
    IFF(O.FULFILLED_QUANTITY < O.ORDERED_QUANTITY, TRUE, FALSE)
        AS FULFILLMENT_GAP_FLAG
FROM CHAINLOOM.RAW.ORDER_LINE O
JOIN CHAINLOOM.RAW.CUSTOMER C
  ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN CHAINLOOM.RAW.PRODUCT P
  ON O.PRODUCT_ID = P.PRODUCT_ID
JOIN CHAINLOOM.RAW.PLANT PL
  ON O.PLANT_ID = PL.PLANT_ID;

CREATE OR REPLACE VIEW V_SHIPMENT_PERFORMANCE
COMMENT = 'Curated shipment performance surface; grain: one row per shipment event'
AS
SELECT
    S.SHIPMENT_ID,
    S.ORDER_LINE_ID,
    S.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CUSTOMER_SEGMENT,
    C.CUSTOMER_REGION,
    C.CUSTOMER_PRIORITY,
    S.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_FAMILY,
    S.PLANT_ID,
    PL.PLANT_NAME,
    PL.REGION AS PLANT_REGION,
    S.CARRIER_ID,
    CA.CARRIER_NAME,
    CA.SERVICE_LEVEL,
    S.SHIP_DATE,
    S.PROMISED_DATE,
    S.ACTUAL_DELIVERY_DATE,
    S.SHIPPED_QUANTITY,
    S.SHIPMENT_STATUS,
    S.DELAY_REASON,
    IFF(
        S.ACTUAL_DELIVERY_DATE IS NOT NULL,
        DATEDIFF('day', S.PROMISED_DATE, S.ACTUAL_DELIVERY_DATE),
        NULL
    ) AS DELIVERY_DELAY_DAYS,
    IFF(
        S.ACTUAL_DELIVERY_DATE IS NOT NULL
        AND S.ACTUAL_DELIVERY_DATE <= S.PROMISED_DATE,
        TRUE,
        FALSE
    ) AS ON_TIME_FLAG,
    IFF(
        S.ACTUAL_DELIVERY_DATE IS NOT NULL,
        TRUE,
        FALSE
    ) AS DELIVERY_ELIGIBLE_FLAG
FROM CHAINLOOM.RAW.SHIPMENT S
JOIN CHAINLOOM.RAW.CUSTOMER C
  ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN CHAINLOOM.RAW.PRODUCT P
  ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN CHAINLOOM.RAW.PLANT PL
  ON S.PLANT_ID = PL.PLANT_ID
JOIN CHAINLOOM.RAW.CARRIER CA
  ON S.CARRIER_ID = CA.CARRIER_ID;
