-- ChainLoom
-- CURATED validation
-- Version: 1.1

USE DATABASE CHAINLOOM;
USE SCHEMA CURATED;

SHOW VIEWS IN SCHEMA CHAINLOOM.CURATED;

SELECT 'V_SUPPLIER_PERFORMANCE' AS VIEW_NAME, COUNT(*) AS ROW_COUNT
FROM V_SUPPLIER_PERFORMANCE
UNION ALL
SELECT 'V_INVENTORY_POSITION', COUNT(*) FROM V_INVENTORY_POSITION
UNION ALL
SELECT 'V_PRODUCTION_PERFORMANCE', COUNT(*) FROM V_PRODUCTION_PERFORMANCE
UNION ALL
SELECT 'V_CUSTOMER_FULFILLMENT', COUNT(*) FROM V_CUSTOMER_FULFILLMENT
UNION ALL
SELECT 'V_SHIPMENT_PERFORMANCE', COUNT(*) FROM V_SHIPMENT_PERFORMANCE;

-- Expected: every query below returns zero rows.
SELECT SUPPLIER_ID, PART_ID, COUNT(*) AS ROWS_AT_GRAIN
FROM V_SUPPLIER_PERFORMANCE
GROUP BY SUPPLIER_ID, PART_ID
HAVING COUNT(*) > 1;

SELECT PART_ID, PLANT_ID, SNAPSHOT_DATE, COUNT(*) AS ROWS_AT_GRAIN
FROM V_INVENTORY_POSITION
GROUP BY PART_ID, PLANT_ID, SNAPSHOT_DATE
HAVING COUNT(*) > 1;

SELECT PLANT_ID, PRODUCT_ID, PRODUCTION_DATE, COUNT(*) AS ROWS_AT_GRAIN
FROM V_PRODUCTION_PERFORMANCE
GROUP BY PLANT_ID, PRODUCT_ID, PRODUCTION_DATE
HAVING COUNT(*) > 1;

SELECT ORDER_LINE_ID, COUNT(*) AS ROWS_AT_GRAIN
FROM V_CUSTOMER_FULFILLMENT
GROUP BY ORDER_LINE_ID
HAVING COUNT(*) > 1;

SELECT SHIPMENT_ID, COUNT(*) AS ROWS_AT_GRAIN
FROM V_SHIPMENT_PERFORMANCE
GROUP BY SHIPMENT_ID
HAVING COUNT(*) > 1;

SELECT
    COUNT(*) AS ROWS_CHECKED,
    SUM(IFF(C.AVAILABLE_QUANTITY = R.AVAILABLE_QUANTITY, 0, 1)) AS MISMATCH_ROWS
FROM V_INVENTORY_POSITION C
JOIN CHAINLOOM.RAW.INVENTORY R
  ON C.INVENTORY_SNAPSHOT_ID = R.INVENTORY_SNAPSHOT_ID;

SELECT
    COUNT(*) AS ROWS_CHECKED,
    SUM(IFF(C.PRODUCED_QUANTITY = R.PRODUCED_QUANTITY, 0, 1)) AS MISMATCH_ROWS
FROM V_PRODUCTION_PERFORMANCE C
JOIN CHAINLOOM.RAW.PRODUCTION R
  ON C.PRODUCTION_ID = R.PRODUCTION_ID;

SELECT
    COUNT(*) AS ROWS_CHECKED,
    SUM(IFF(C.FULFILLED_QUANTITY = R.FULFILLED_QUANTITY, 0, 1)) AS MISMATCH_ROWS
FROM V_CUSTOMER_FULFILLMENT C
JOIN CHAINLOOM.RAW.ORDER_LINE R
  ON C.ORDER_LINE_ID = R.ORDER_LINE_ID;

SELECT
    COUNT(*) AS ROWS_CHECKED,
    SUM(IFF(C.SHIPPED_QUANTITY = R.SHIPPED_QUANTITY, 0, 1)) AS MISMATCH_ROWS
FROM V_SHIPMENT_PERFORMANCE C
JOIN CHAINLOOM.RAW.SHIPMENT R
  ON C.SHIPMENT_ID = R.SHIPMENT_ID;

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CRITICAL_PART_COUNT,
    CRITICAL_PARTS,
    P104_EXPOSURE_FLAG,
    P104_QTY_PER_PRODUCT
FROM V_PRODUCTION_PERFORMANCE
WHERE P104_EXPOSURE_FLAG = TRUE
  AND PLANT_ID = 'PL03'
GROUP BY
    PRODUCT_ID,
    PRODUCT_NAME,
    CRITICAL_PART_COUNT,
    CRITICAL_PARTS,
    P104_EXPOSURE_FLAG,
    P104_QTY_PER_PRODUCT
ORDER BY PRODUCT_ID;
