CREATE OR REPLACE VIEW CHAINLOOM.CURATED.V_PRODUCT_RISK_SIGNALS
COMMENT = 'Governed product-level risk signal summary. Grain: one row per product. Each signal (fulfillment, delivery, production) is independently computed from its respective CURATED analytical surface. RISK_SIGNAL_COUNT counts co-occurring risk indicators but does NOT imply causality between signals. Thresholds: fulfillment < 0.90, OTD < 0.85, attainment < 0.90.'
AS
WITH product_universe AS (
    SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME FROM CHAINLOOM.CURATED.V_CUSTOMER_FULFILLMENT
    UNION
    SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME FROM CHAINLOOM.CURATED.V_SHIPMENT_PERFORMANCE
    UNION
    SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME FROM CHAINLOOM.CURATED.V_PRODUCTION_PERFORMANCE
),
fulfillment_signal AS (
    SELECT
        PRODUCT_ID,
        SUM(FULFILLED_QUANTITY) / NULLIF(SUM(ORDERED_QUANTITY), 0) AS FULFILLMENT_RATE,
        COUNT_IF(FULFILLMENT_GAP_FLAG = TRUE) AS ORDER_LINES_WITH_GAPS,
        COUNT(*) AS TOTAL_ORDER_LINES
    FROM CHAINLOOM.CURATED.V_CUSTOMER_FULFILLMENT
    GROUP BY PRODUCT_ID
),
delivery_signal AS (
    SELECT
        PRODUCT_ID,
        COUNT_IF(ON_TIME_FLAG = TRUE) / NULLIF(COUNT_IF(DELIVERY_ELIGIBLE_FLAG = TRUE), 0) AS ON_TIME_DELIVERY_RATE,
        COUNT_IF(DELIVERY_ELIGIBLE_FLAG = TRUE) AS ELIGIBLE_SHIPMENTS
    FROM CHAINLOOM.CURATED.V_SHIPMENT_PERFORMANCE
    GROUP BY PRODUCT_ID
),
production_signal AS (
    SELECT
        PRODUCT_ID,
        SUM(PRODUCED_QUANTITY) / NULLIF(SUM(PLANNED_QUANTITY), 0) AS PRODUCTION_ATTAINMENT,
        COUNT_IF(CONSTRAINT_FLAG = TRUE) AS CONSTRAINED_DAYS,
        COUNT(*) AS TOTAL_PRODUCTION_DAYS
    FROM CHAINLOOM.CURATED.V_PRODUCTION_PERFORMANCE
    GROUP BY PRODUCT_ID
)
SELECT
    pu.PRODUCT_ID,
    pu.PRODUCT_NAME,
    f.FULFILLMENT_RATE,
    COALESCE(f.ORDER_LINES_WITH_GAPS, 0) AS ORDER_LINES_WITH_GAPS,
    COALESCE(f.TOTAL_ORDER_LINES, 0) AS TOTAL_ORDER_LINES,
    IFF(f.FULFILLMENT_RATE < 0.90, TRUE, FALSE) AS FULFILLMENT_RISK_FLAG,
    d.ON_TIME_DELIVERY_RATE,
    COALESCE(d.ELIGIBLE_SHIPMENTS, 0) AS ELIGIBLE_SHIPMENTS,
    IFF(d.ON_TIME_DELIVERY_RATE < 0.85, TRUE, FALSE) AS DELIVERY_RISK_FLAG,
    p.PRODUCTION_ATTAINMENT,
    COALESCE(p.CONSTRAINED_DAYS, 0) AS CONSTRAINED_DAYS,
    COALESCE(p.TOTAL_PRODUCTION_DAYS, 0) AS TOTAL_PRODUCTION_DAYS,
    IFF(p.PRODUCTION_ATTAINMENT < 0.90, TRUE, FALSE) AS PRODUCTION_RISK_FLAG,
    (IFF(f.FULFILLMENT_RATE < 0.90, 1, 0)
     + IFF(d.ON_TIME_DELIVERY_RATE < 0.85, 1, 0)
     + IFF(p.PRODUCTION_ATTAINMENT < 0.90, 1, 0)) AS RISK_SIGNAL_COUNT
FROM product_universe pu
LEFT JOIN fulfillment_signal f ON pu.PRODUCT_ID = f.PRODUCT_ID
LEFT JOIN delivery_signal d ON pu.PRODUCT_ID = d.PRODUCT_ID
LEFT JOIN production_signal p ON pu.PRODUCT_ID = p.PRODUCT_ID;
